### PR TITLE
Remove JS font loader

### PR DESCRIPTION
**Pull request by robinwhittleton**
The JS font loader from Google appears to be vestigial. We can get rid of it, and rework the loading of fonts in IE8 to use just the CSS file. This appears to work for me in test environments, but if anyone has any more context as to why it’s stuck around then please comment before this gets merged.

Will fix https://github.com/alphagov/govuk_template/issues/216 . I did some investigation in https://github.com/alphagov/govuk_template/issues/216#issuecomment-222657594 which might be pertinent.

### CODE REVIEW

**Comment by mcgoooo** [comment]
looks good to me :+1: although i would probs remove the ie6 include by now, surely :trollface:

**Comment by accessiblewebuk** [comment]
I have learnt a new word "vestigial" - don't tell any content designers.

**Comment by robinwhittleton** [comment]
Looking at the loader code, it sets (according to state) a set of `.wf-*` classes that let you style the site during the loading phase of the font. We’re not using any of these in the rest of the code. We’re also not using any of the provided callback hooks in our JS.

**Comment by tvararu** [comment]
👌  Looks good to me.

**Comment by nickcolley** [comment]
💣  👍

**Pull request merged**
