### PR TITLE
Add webjar packager, spec and update README.md

### PR DESCRIPTION
**Pull request by ijmad**
Hello, this is some code to build the assets in to a WebJar. I'd like this for my project. Let me know if my Ruby is OK because I write it poorly.

### CODE REVIEW

**Comment by bradleywright** [comment]
Awesome, thanks @ijmad.

Do we need to push the WebJar anywhere, or are you intending to use this library directly in your build process?

**Comment by ijmad** [comment]
We do need to host it somewhere, but it needs to go somewhere that looks like a Maven/Ivy repository, and we currently don't have a Nexus or similar. The structure of these repos isn't a great match for github's release manager.

It is possible though, via some mild hacking, to do this with a Maven plugin that GitHub provides, which I've been doing over here - https://github.com/alphagov/govuk_template_jar/ (see https://github.com/alphagov/govuk_template_jar/tree/mvn-repo for the fake repo).

I could fold this in to govuk_template as well, but it is a bit messy.
General thoughts welcome, and/or a better option if you can think of one.

**Comment by bradleywright** [comment]
I just wanted to check if you had any thoughts about hosting before I merged this - I've tested it on a GOV.UK Vagrant machine and it builds correctly, so I think it's good to merge.

We can revisit hosting of the JAR later.

**Comment by bradleywright** [comment]
:+1:

**Comment by ijmad** [comment]
No worries - we can have a chat about that at some point!

**Comment by jamiecobbett** [comment]
When I build the webjar, it doesn't seem to include the view (`govuk_template.html`). Is this deliberate?

**Comment by jamiecobbett** [comment]
Spoke with @ijmad in person, and yes it is deliberate because webjars aren't for templates/html. I've tweaked the README to make this clearer over in https://github.com/alphagov/govuk_template/pull/146

**Pull request merged**
