### PR TITLE
Fix negative offset on crown SVG causing left blob to be chopped

### PR DESCRIPTION
**Pull request by andymantell**

### CODE REVIEW

**Comment by nickcolley** [comment]
Nice! Can you show some screenshots? 👍

**Comment by andymantell** [comment]
Before:

image

After:

image

**Comment by andymantell** [comment]
@nickcolley It looks like it's actually only used in Safari's pinned tabs though which is rendered so so small that it's imperceptible! The only reason I noticed is I was looking for an SVG copy of the crown to go in a PDF...

**Comment by nickcolley** [comment]
Looks sounds as a 💷  👍

**Comment by andymantell** [comment]
:+1:

**Pull request merged**
