### PR TITLE
Add deprecation notice and styles for the website

### PR DESCRIPTION
**Pull request by igloosi**
This is to be merged to the `gh-pages` branch
Also my editor is set to remove trailing whitespace....

### CODE REVIEW

**Comment by joelanman** [comment]
Should we say we are no longer supporting other templating languages?

**Comment by 36degrees** [comment]
I think these changes will both be overwritten by the [DocsPublisher](https://github.com/alphagov/govuk_template/blob/master/build_tools/publisher/docs_publisher.rb#L35-L48) the next time we do a release.

I believe these changes need to be made to the [`data/index.yml`](https://github.com/alphagov/govuk_template/blob/gh-pages/data/index.yml) file which is used to generate the HTML files.

I think the extra styles should probably be either made inline or added to the style block at the top of that 'data file', as the stylesheet will be regenerated as well.

We'll then need to run the DocsPublisher by itself – annoyingly it looks like that can't be done without creating a release, so we may need to update the Rakefile and .travis.yml to make that possible…

**Comment by igloosi** [comment]
give me strength...

**Comment by igloosi** [comment]
closing, as we'll just go with the notice in the README.md

**Pull request closed without merging**
