### PR TITLE
Upgrade insecure links to https

### LINKED ISSUE #330: Broken and insecure links
Noticed a few dodgy links. PR incoming :-)

### PR DESCRIPTION
**Pull request by edent**
Fixes #330

### CODE REVIEW

**Comment by 36degrees** [comment]
Thanks for this @edent!

Unfortunately there's a [few failing specs](https://travis-ci.org/alphagov/govuk_template/builds/289045582) as the output no longer matches the specced example files  – specifically for [EJS](https://github.com/alphagov/govuk_template/blob/master/spec/support/examples/package_ejs.json#L12) and [mustache](https://github.com/alphagov/govuk_template/blob/master/spec/support/examples/package.json#L12)

Would you be able to update those examples so we can get the tests passing again?

**Comment by edent** [comment]
D'oh! Fixed.

**Comment by 36degrees** [comment]
Thanks! Would you be able to squash those commits together?

**Comment by edent** [comment]
Hmm, can't see a way to do that on the mobile website, sorry! I think you have to do it as maintainer.

**Comment by 36degrees** [comment]
Superseded by #334

**Pull request closed without merging**
