### PR TITLE
Updated favicon icons to remove invalid html and modernise

### PR DESCRIPTION
**Pull request by igloosi**
Updates apple touch icon sizes and syntax that follow Apple spec
https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html
and
https://developer.apple.com/ios/human-interface-guidelines/graphics/app-icon/

This also makes html valid according to W3C

W3C validator before
screen shot 2017-05-12 at 10 59 31

W3C validator after
screen shot 2017-05-12 at 11 25 47

Note: tested by manual upload of the current gov.uk source and replaced declaration

### CODE REVIEW

**Comment by nickcolley** [comment]
Nice! @igloosi can you show how you've tested this?

**Comment by igloosi** [comment]
screenshots attached

**Comment by nickcolley** [comment]
@igloosi I was thinking how the icons render on devices?

**Comment by igloosi** [comment]
oh that. would need to build this branch somewhere i guess

**Comment by igloosi** [comment]
after a long, needlessly complicated procedure to get template up and running, here are screeshots from browserstack device emulator
screen shot 2017-05-12 at 16 58 07
screen shot 2017-05-12 at 17 01 45

**Comment by 36degrees** [comment]
For the curious, the `-precomposed` suffix _used_ to instruct iOS not to add effects (drop shadow and 'a reflective shine')

> As of iOS 7, no special effects are applied to touch icons anymore, so if you only care about iOS 7 and up you don’t have to use precomposed anymore.
– https://mathiasbynens.be/notes/touch-icons

IMO that's fine.

**Comment by igloosi** [comment]
yeah, ios 7 is ancient :)

**Comment by fofr** [comment]
This has had an interesting (and unexpected) affect on Static:
https://github.com/alphagov/static/pull/1041

**Pull request merged**
